stages:
    - test

unit-test:
    stage: test
    image: python:latest
    before_script:
        - python -V
       
    script: 
        - pip3 install virtualenv 
        - virtualenv challenge_venv
        - source challenge_venv/bin/activate
        - pip install -r requirements.txt
        - pip install pytest pytest-cov
        - python -m pytest --cov-report=html --cov=src .

