name: Unit Tests
on: push
jobs:
  go-tests:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.13.1
      - uses: autero1/action-terraform@v0.1.0
        with:
          terraform_version: 1.0.11
      - name: Download Go Modules
        working-directory: test
        run: 
          go mod download
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Go Tests
        working-directory: test
        run: go test -v -tags=unit
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}